---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create DBSubnetGroup*1, ParameterGroup*1

Parameters:
  ProjectName:
    Type: String
    Default: Practice
    Description: Project Name
  LinkedStackVPC:
    Type: String
    Default: vpc-test-VPC
    Description: Linked Stack Export Name for VPC
  LinkedStackPrivateSubnet1:
    Type: String
    Default: vpc-test-PrivateSubnet1
    Description: Linked Stack Export Name for PrivateSubnet1
  LinkedStackPrivateSubnet2:
    Type: String
    Default: vpc-test-PrivateSubnet2
    Description: Linked Stack Export Name for PrivateSubnet2

Resources:
  DBSubnetGroup1:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Group 01
      DBSubnetGroupName: !Sub "${ProjectName}-dbsubgroup-01"
      SubnetIds:
        - Fn::ImportValue: !Sub "${LinkedStackPrivateSubnet1}"
        - Fn::ImportValue: !Sub "${LinkedStackPrivateSubnet2}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-dbsubgroup-01"
